### ISSUE TITLE
Hard Drive List not removing already collected hard drives

### ISSUE THREAD

**Issue by ApocalypticNyghtmare** [AnthorNet/SC-InteractiveMap#433]
# Issue
When loading a save in the interactive map then opening the Hard Drive list, it does not remove the hard drives that have already been found.

## Replication
1. Open save in interactive map
2. Open Hard Drive tab

### Expected Result
Hard Drives list should show x/118 and remove found hard drives from the list.

**Comment by AnthorNet** [comment]
Try to refresh your cache as it seems to work properly on my side.
If not please send test save with a hard drive should be collected and not shown as being.

**Comment by picikCZE** [comment]
I am having the same issue. While the map shows 20/118 the hard drive tab shows 3/118. I tried it on 2 different computers.

**Comment by AnthorNet** [comment]
> I am having the same issue. While the map shows 20/118 the hard drive tab shows 3/118. I tried it on 2 different computers.

Can I get your save?

**Comment by picikCZE** [comment]
> > I am having the same issue. While the map shows 20/118 the hard drive tab shows 3/118. I tried it on 2 different computers.
> 
> Can I get your save?

I´ve colledcted more, but the problem still stands.

I couldn´t upload the save into the response, so here you go: https://github.com/picikCZE/save

![Image](https://github.com/user-attachments/assets/f9a97df1-3ee4-4ca5-ad94-50b063aabd34)
![Image](https://github.com/user-attachments/assets/a620d26b-d2a8-4b59-9d8a-b1fa7be6f3e0)
![Image](https://github.com/user-attachments/assets/90c0c375-7563-414b-ae36-40dab5ce0ef8)

**Comment by AnthorNet** [comment]
Seen it, should be fixed internally

**Comment by picikCZE** [comment]
It still wasnt fixed for me. Even on a different pc, browser or save

**Comment by FlatCapElectronics** [comment]
Same issue. Tried clearing browser cache and cookies, Used Firefox and Chromium. Always the same result, one of 118 found.
I've included my save, renamed with a .txt on the end to placate the upload filter.

[test.sav.txt](https://github.com/user-attachments/files/21246343/test.sav.txt)
